//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateCounsel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssociateCounsel()
        {
            this.PersonnelRequests = new HashSet<PersonnelRequest>();
        }
    
        public int FirmID { get; set; }
        public string FirmName { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<bool> Check { get; set; }
        public string W9Image { get; set; }
        public Nullable<bool> W9 { get; set; }
        public string Country { get; set; }
        public string Telephone1 { get; set; }
        public string Ext { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> GB { get; set; }
        public Nullable<bool> ALQ { get; set; }
        public Nullable<bool> WH { get; set; }
        public string FederalTaxID { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<byte> DoNotUse { get; set; }
        public string Notes { get; set; }

        public string fileNumber { get; set; }
        public Nullable<int> localCounselStatus { get; set; }
        public Nullable<double> localCounselRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelRequest> PersonnelRequests { get; set; }
    }
}
