//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public string DocumentName { get; set; }
        public string FileName { get; set; }
        public string StateCode { get; set; }
        public string DocumentType { get; set; }
        public string ProjectType { get; set; }
        public string FormType { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> PracticeAreaID { get; set; }
        public string WFJFileNbr { get; set; }
        public Nullable<int> Days { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> EmployeeCategoryID { get; set; }
        public string StateCodeID { get; set; }
        public string DocumentTypeID { get; set; }
        public string ProjectTypeID { get; set; }
        public string FormTypeID { get; set; }
        public Nullable<int> SeqNo { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PracticeArea PracticeArea { get; set; }
    }
}
