//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormField()
        {
            this.FormSelectionLists = new HashSet<FormSelectionList>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> FieldTypeID { get; set; }
        public Nullable<int> formSectionID { get; set; }
        public Nullable<byte> Required { get; set; }
        public Nullable<int> Length { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> ListSeqNo { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public Nullable<byte> EMailField { get; set; }
        public Nullable<int> SelectionColumn { get; set; }
        public string EPDBFieldName { get; set; }
        public string SQLStatement { get; set; }
        public Nullable<int> AccountSummarySeqNo { get; set; }
        public Nullable<byte> showOnCalendar { get; set; }
        public Nullable<int> rowNumber { get; set; }
        public Nullable<int> fieldSizeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormSelectionList> FormSelectionLists { get; set; }
        public virtual fieldSize fieldSize { get; set; }
    }
}
