//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int ID { get; set; }
        public string FormName { get; set; }
        public Nullable<int> FormTypeID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> AccountBalanceFieldID { get; set; }
        public Nullable<int> TotalPaymentsFieldID { get; set; }
        public Nullable<int> CustomerNameFieldID { get; set; }
        public Nullable<int> WFJFileNbrFieldID { get; set; }
        public Nullable<int> CustomerAccountFieldID { get; set; }
        public Nullable<int> JobNumberFieldID { get; set; }
        public Nullable<int> DefaultRequestorID { get; set; }
        public Nullable<byte> hasCollector { get; set; }
        public Nullable<byte> hasAdmin { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<int> ClientNumber { get; set; }
    }
}
