//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Requests = new HashSet<Request>();
            this.Users = new HashSet<User>();
            this.PersonnelClients = new HashSet<PersonnelClient>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public string Image { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string ProfessionalOrganizations { get; set; }
        public string StateBar { get; set; }
        public string FederalBar { get; set; }
        public string Education { get; set; }
        public string Publications { get; set; }
        public string Cases { get; set; }
        public Nullable<byte> TraneAttorney { get; set; }
        public string OtherExperience { get; set; }
        public string HonorsAwards { get; set; }
        public string SuccessStories { get; set; }
        public string CommunityActivities { get; set; }
        public Nullable<byte> isShareholder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelClient> PersonnelClients { get; set; }
    }
}
